// Code generated by Kitex v0.15.4. DO NOT EDIT.

package customerservice

import (
	"context"
	customer "example_shop/service/customer/kitex_gen/customer"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetCustomerService(ctx context.Context, req *customer.GetCustomerServiceReq, callOptions ...callopt.Option) (r *customer.GetCustomerServiceResp, err error)
	ListCustomerService(ctx context.Context, req *customer.ListCustomerServiceReq, callOptions ...callopt.Option) (r *customer.ListCustomerServiceResp, err error)
	CreateShiftConfig(ctx context.Context, req *customer.CreateShiftConfigReq, callOptions ...callopt.Option) (r *customer.CreateShiftConfigResp, err error)
	ListShiftConfig(ctx context.Context, req *customer.ListShiftConfigReq, callOptions ...callopt.Option) (r *customer.ListShiftConfigResp, err error)
	UpdateShiftConfig(ctx context.Context, req *customer.UpdateShiftConfigReq, callOptions ...callopt.Option) (r *customer.UpdateShiftConfigResp, err error)
	DeleteShiftConfig(ctx context.Context, req *customer.DeleteShiftConfigReq, callOptions ...callopt.Option) (r *customer.DeleteShiftConfigResp, err error)
	AssignSchedule(ctx context.Context, req *customer.AssignScheduleReq, callOptions ...callopt.Option) (r *customer.AssignScheduleResp, err error)
	ListScheduleGrid(ctx context.Context, req *customer.ListScheduleGridReq, callOptions ...callopt.Option) (r *customer.ListScheduleGridResp, err error)
	UpsertScheduleCell(ctx context.Context, req *customer.UpsertScheduleCellReq, callOptions ...callopt.Option) (r *customer.UpsertScheduleCellResp, err error)
	AutoSchedule(ctx context.Context, req *customer.AutoScheduleReq, callOptions ...callopt.Option) (r *customer.AutoScheduleResp, err error)
	AssignCustomer(ctx context.Context, req *customer.AssignCustomerReq, callOptions ...callopt.Option) (r *customer.AssignCustomerResp, err error)
	CreateConversation(ctx context.Context, req *customer.CreateConversationReq, callOptions ...callopt.Option) (r *customer.CreateConversationResp, err error)
	EndConversation(ctx context.Context, req *customer.EndConversationReq, callOptions ...callopt.Option) (r *customer.EndConversationResp, err error)
	TransferConversation(ctx context.Context, req *customer.TransferConversationReq, callOptions ...callopt.Option) (r *customer.TransferConversationResp, err error)
	ApplyLeaveTransfer(ctx context.Context, req *customer.ApplyLeaveTransferReq, callOptions ...callopt.Option) (r *customer.ApplyLeaveTransferResp, err error)
	ApproveLeaveTransfer(ctx context.Context, req *customer.ApproveLeaveTransferReq, callOptions ...callopt.Option) (r *customer.ApproveLeaveTransferResp, err error)
	GetLeaveTransfer(ctx context.Context, req *customer.GetLeaveTransferReq, callOptions ...callopt.Option) (r *customer.GetLeaveTransferResp, err error)
	ListLeaveTransfer(ctx context.Context, req *customer.ListLeaveTransferReq, callOptions ...callopt.Option) (r *customer.ListLeaveTransferResp, err error)
	GetLeaveAuditLog(ctx context.Context, req *customer.GetLeaveAuditLogReq, callOptions ...callopt.Option) (r *customer.GetLeaveAuditLogResp, err error)
	ApplyChainSwap(ctx context.Context, req *customer.ApplyChainSwapReq, callOptions ...callopt.Option) (r *customer.ApplyChainSwapResp, err error)
	ApproveChainSwap(ctx context.Context, req *customer.ApproveChainSwapReq, callOptions ...callopt.Option) (r *customer.ApproveChainSwapResp, err error)
	ListChainSwap(ctx context.Context, req *customer.ListChainSwapReq, callOptions ...callopt.Option) (r *customer.ListChainSwapResp, err error)
	GetChainSwap(ctx context.Context, req *customer.GetChainSwapReq, callOptions ...callopt.Option) (r *customer.GetChainSwapResp, err error)
	Heartbeat(ctx context.Context, req *customer.HeartbeatReq, callOptions ...callopt.Option) (r *customer.HeartbeatResp, err error)
	ListOnlineCustomers(ctx context.Context, req *customer.ListOnlineCustomersReq, callOptions ...callopt.Option) (r *customer.ListOnlineCustomersResp, err error)
	GetSwapCandidates(ctx context.Context, req *customer.GetSwapCandidatesReq, callOptions ...callopt.Option) (r *customer.GetSwapCandidatesResp, err error)
	CheckSwapConflict(ctx context.Context, req *customer.CheckSwapConflictReq, callOptions ...callopt.Option) (r *customer.CheckSwapConflictResp, err error)
	ListConversation(ctx context.Context, req *customer.ListConversationReq, callOptions ...callopt.Option) (r *customer.ListConversationResp, err error)
	ListConversationHistory(ctx context.Context, req *customer.ListConversationHistoryReq, callOptions ...callopt.Option) (r *customer.ListConversationResp, err error)
	ListConversationMessage(ctx context.Context, req *customer.ListConversationMessageReq, callOptions ...callopt.Option) (r *customer.ListConversationMessageResp, err error)
	SendConversationMessage(ctx context.Context, req *customer.SendConversationMessageReq, callOptions ...callopt.Option) (r *customer.SendConversationMessageResp, err error)
	ListQuickReply(ctx context.Context, req *customer.ListQuickReplyReq, callOptions ...callopt.Option) (r *customer.ListQuickReplyResp, err error)
	CreateQuickReply(ctx context.Context, req *customer.CreateQuickReplyReq, callOptions ...callopt.Option) (r *customer.CreateQuickReplyResp, err error)
	UpdateQuickReply(ctx context.Context, req *customer.UpdateQuickReplyReq, callOptions ...callopt.Option) (r *customer.UpdateQuickReplyResp, err error)
	DeleteQuickReply(ctx context.Context, req *customer.DeleteQuickReplyReq, callOptions ...callopt.Option) (r *customer.DeleteQuickReplyResp, err error)
	CreateConvCategory(ctx context.Context, req *customer.CreateConvCategoryReq, callOptions ...callopt.Option) (r *customer.CreateConvCategoryResp, err error)
	ListConvCategory(ctx context.Context, req *customer.ListConvCategoryReq, callOptions ...callopt.Option) (r *customer.ListConvCategoryResp, err error)
	UpdateConversationClassify(ctx context.Context, req *customer.UpdateConversationClassifyReq, callOptions ...callopt.Option) (r *customer.UpdateConversationClassifyResp, err error)
	CreateConvTag(ctx context.Context, req *customer.CreateConvTagReq, callOptions ...callopt.Option) (r *customer.CreateConvTagResp, err error)
	ListConvTag(ctx context.Context, req *customer.ListConvTagReq, callOptions ...callopt.Option) (r *customer.ListConvTagResp, err error)
	UpdateConvTag(ctx context.Context, req *customer.UpdateConvTagReq, callOptions ...callopt.Option) (r *customer.UpdateConvTagResp, err error)
	DeleteConvTag(ctx context.Context, req *customer.DeleteConvTagReq, callOptions ...callopt.Option) (r *customer.DeleteConvTagResp, err error)
	GetConversationStats(ctx context.Context, req *customer.GetConversationStatsReq, callOptions ...callopt.Option) (r *customer.GetConversationStatsResp, err error)
	GetConversationMonitor(ctx context.Context, req *customer.GetConversationMonitorReq, callOptions ...callopt.Option) (r *customer.GetConversationMonitorResp, err error)
	ExportConversations(ctx context.Context, req *customer.ExportConversationsReq, callOptions ...callopt.Option) (r *customer.ExportConversationsResp, err error)
	MsgAutoClassify(ctx context.Context, req *customer.MsgAutoClassifyReq, callOptions ...callopt.Option) (r *customer.MsgAutoClassifyResp, err error)
	AdjustMsgClassify(ctx context.Context, req *customer.AdjustMsgClassifyReq, callOptions ...callopt.Option) (r *customer.AdjustMsgClassifyResp, err error)
	GetClassifyStats(ctx context.Context, req *customer.GetClassifyStatsReq, callOptions ...callopt.Option) (r *customer.GetClassifyStatsResp, err error)
	CreateMsgCategory(ctx context.Context, req *customer.CreateMsgCategoryReq, callOptions ...callopt.Option) (r *customer.CreateMsgCategoryResp, err error)
	ListMsgCategory(ctx context.Context, req *customer.ListMsgCategoryReq, callOptions ...callopt.Option) (r *customer.ListMsgCategoryResp, err error)
	UpdateMsgCategory(ctx context.Context, req *customer.UpdateMsgCategoryReq, callOptions ...callopt.Option) (r *customer.UpdateMsgCategoryResp, err error)
	DeleteMsgCategory(ctx context.Context, req *customer.DeleteMsgCategoryReq, callOptions ...callopt.Option) (r *customer.DeleteMsgCategoryResp, err error)
	Login(ctx context.Context, req *customer.LoginReq, callOptions ...callopt.Option) (r *customer.LoginResp, err error)
	GetCurrentUser(ctx context.Context, req *customer.GetCurrentUserReq, callOptions ...callopt.Option) (r *customer.GetCurrentUserResp, err error)
	Register(ctx context.Context, req *customer.RegisterReq, callOptions ...callopt.Option) (r *customer.RegisterResp, err error)
	Logout(ctx context.Context, req *customer.LogoutReq, callOptions ...callopt.Option) (r *customer.LogoutResp, err error)
	EncryptMessage(ctx context.Context, req *customer.EncryptMessageReq, callOptions ...callopt.Option) (r *customer.EncryptMessageResp, err error)
	DecryptMessage(ctx context.Context, req *customer.DecryptMessageReq, callOptions ...callopt.Option) (r *customer.DecryptMessageResp, err error)
	DesensitizeMessage(ctx context.Context, req *customer.DesensitizeMessageReq, callOptions ...callopt.Option) (r *customer.DesensitizeMessageResp, err error)
	ArchiveConversations(ctx context.Context, req *customer.ArchiveConversationsReq, callOptions ...callopt.Option) (r *customer.ArchiveConversationsResp, err error)
	GetArchiveTask(ctx context.Context, req *customer.GetArchiveTaskReq, callOptions ...callopt.Option) (r *customer.GetArchiveTaskResp, err error)
	QueryArchivedConversation(ctx context.Context, req *customer.QueryArchivedConversationReq, callOptions ...callopt.Option) (r *customer.QueryArchivedConversationResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kCustomerServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kCustomerServiceClient struct {
	*kClient
}

func (p *kCustomerServiceClient) GetCustomerService(ctx context.Context, req *customer.GetCustomerServiceReq, callOptions ...callopt.Option) (r *customer.GetCustomerServiceResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetCustomerService(ctx, req)
}

func (p *kCustomerServiceClient) ListCustomerService(ctx context.Context, req *customer.ListCustomerServiceReq, callOptions ...callopt.Option) (r *customer.ListCustomerServiceResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListCustomerService(ctx, req)
}

func (p *kCustomerServiceClient) CreateShiftConfig(ctx context.Context, req *customer.CreateShiftConfigReq, callOptions ...callopt.Option) (r *customer.CreateShiftConfigResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateShiftConfig(ctx, req)
}

func (p *kCustomerServiceClient) ListShiftConfig(ctx context.Context, req *customer.ListShiftConfigReq, callOptions ...callopt.Option) (r *customer.ListShiftConfigResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListShiftConfig(ctx, req)
}

func (p *kCustomerServiceClient) UpdateShiftConfig(ctx context.Context, req *customer.UpdateShiftConfigReq, callOptions ...callopt.Option) (r *customer.UpdateShiftConfigResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateShiftConfig(ctx, req)
}

func (p *kCustomerServiceClient) DeleteShiftConfig(ctx context.Context, req *customer.DeleteShiftConfigReq, callOptions ...callopt.Option) (r *customer.DeleteShiftConfigResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteShiftConfig(ctx, req)
}

func (p *kCustomerServiceClient) AssignSchedule(ctx context.Context, req *customer.AssignScheduleReq, callOptions ...callopt.Option) (r *customer.AssignScheduleResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AssignSchedule(ctx, req)
}

func (p *kCustomerServiceClient) ListScheduleGrid(ctx context.Context, req *customer.ListScheduleGridReq, callOptions ...callopt.Option) (r *customer.ListScheduleGridResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListScheduleGrid(ctx, req)
}

func (p *kCustomerServiceClient) UpsertScheduleCell(ctx context.Context, req *customer.UpsertScheduleCellReq, callOptions ...callopt.Option) (r *customer.UpsertScheduleCellResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpsertScheduleCell(ctx, req)
}

func (p *kCustomerServiceClient) AutoSchedule(ctx context.Context, req *customer.AutoScheduleReq, callOptions ...callopt.Option) (r *customer.AutoScheduleResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AutoSchedule(ctx, req)
}

func (p *kCustomerServiceClient) AssignCustomer(ctx context.Context, req *customer.AssignCustomerReq, callOptions ...callopt.Option) (r *customer.AssignCustomerResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AssignCustomer(ctx, req)
}

func (p *kCustomerServiceClient) CreateConversation(ctx context.Context, req *customer.CreateConversationReq, callOptions ...callopt.Option) (r *customer.CreateConversationResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateConversation(ctx, req)
}

func (p *kCustomerServiceClient) EndConversation(ctx context.Context, req *customer.EndConversationReq, callOptions ...callopt.Option) (r *customer.EndConversationResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.EndConversation(ctx, req)
}

func (p *kCustomerServiceClient) TransferConversation(ctx context.Context, req *customer.TransferConversationReq, callOptions ...callopt.Option) (r *customer.TransferConversationResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.TransferConversation(ctx, req)
}

func (p *kCustomerServiceClient) ApplyLeaveTransfer(ctx context.Context, req *customer.ApplyLeaveTransferReq, callOptions ...callopt.Option) (r *customer.ApplyLeaveTransferResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ApplyLeaveTransfer(ctx, req)
}

func (p *kCustomerServiceClient) ApproveLeaveTransfer(ctx context.Context, req *customer.ApproveLeaveTransferReq, callOptions ...callopt.Option) (r *customer.ApproveLeaveTransferResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ApproveLeaveTransfer(ctx, req)
}

func (p *kCustomerServiceClient) GetLeaveTransfer(ctx context.Context, req *customer.GetLeaveTransferReq, callOptions ...callopt.Option) (r *customer.GetLeaveTransferResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetLeaveTransfer(ctx, req)
}

func (p *kCustomerServiceClient) ListLeaveTransfer(ctx context.Context, req *customer.ListLeaveTransferReq, callOptions ...callopt.Option) (r *customer.ListLeaveTransferResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListLeaveTransfer(ctx, req)
}

func (p *kCustomerServiceClient) GetLeaveAuditLog(ctx context.Context, req *customer.GetLeaveAuditLogReq, callOptions ...callopt.Option) (r *customer.GetLeaveAuditLogResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetLeaveAuditLog(ctx, req)
}

func (p *kCustomerServiceClient) ApplyChainSwap(ctx context.Context, req *customer.ApplyChainSwapReq, callOptions ...callopt.Option) (r *customer.ApplyChainSwapResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ApplyChainSwap(ctx, req)
}

func (p *kCustomerServiceClient) ApproveChainSwap(ctx context.Context, req *customer.ApproveChainSwapReq, callOptions ...callopt.Option) (r *customer.ApproveChainSwapResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ApproveChainSwap(ctx, req)
}

func (p *kCustomerServiceClient) ListChainSwap(ctx context.Context, req *customer.ListChainSwapReq, callOptions ...callopt.Option) (r *customer.ListChainSwapResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListChainSwap(ctx, req)
}

func (p *kCustomerServiceClient) GetChainSwap(ctx context.Context, req *customer.GetChainSwapReq, callOptions ...callopt.Option) (r *customer.GetChainSwapResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetChainSwap(ctx, req)
}

func (p *kCustomerServiceClient) Heartbeat(ctx context.Context, req *customer.HeartbeatReq, callOptions ...callopt.Option) (r *customer.HeartbeatResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Heartbeat(ctx, req)
}

func (p *kCustomerServiceClient) ListOnlineCustomers(ctx context.Context, req *customer.ListOnlineCustomersReq, callOptions ...callopt.Option) (r *customer.ListOnlineCustomersResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListOnlineCustomers(ctx, req)
}

func (p *kCustomerServiceClient) GetSwapCandidates(ctx context.Context, req *customer.GetSwapCandidatesReq, callOptions ...callopt.Option) (r *customer.GetSwapCandidatesResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetSwapCandidates(ctx, req)
}

func (p *kCustomerServiceClient) CheckSwapConflict(ctx context.Context, req *customer.CheckSwapConflictReq, callOptions ...callopt.Option) (r *customer.CheckSwapConflictResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CheckSwapConflict(ctx, req)
}

func (p *kCustomerServiceClient) ListConversation(ctx context.Context, req *customer.ListConversationReq, callOptions ...callopt.Option) (r *customer.ListConversationResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListConversation(ctx, req)
}

func (p *kCustomerServiceClient) ListConversationHistory(ctx context.Context, req *customer.ListConversationHistoryReq, callOptions ...callopt.Option) (r *customer.ListConversationResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListConversationHistory(ctx, req)
}

func (p *kCustomerServiceClient) ListConversationMessage(ctx context.Context, req *customer.ListConversationMessageReq, callOptions ...callopt.Option) (r *customer.ListConversationMessageResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListConversationMessage(ctx, req)
}

func (p *kCustomerServiceClient) SendConversationMessage(ctx context.Context, req *customer.SendConversationMessageReq, callOptions ...callopt.Option) (r *customer.SendConversationMessageResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SendConversationMessage(ctx, req)
}

func (p *kCustomerServiceClient) ListQuickReply(ctx context.Context, req *customer.ListQuickReplyReq, callOptions ...callopt.Option) (r *customer.ListQuickReplyResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListQuickReply(ctx, req)
}

func (p *kCustomerServiceClient) CreateQuickReply(ctx context.Context, req *customer.CreateQuickReplyReq, callOptions ...callopt.Option) (r *customer.CreateQuickReplyResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateQuickReply(ctx, req)
}

func (p *kCustomerServiceClient) UpdateQuickReply(ctx context.Context, req *customer.UpdateQuickReplyReq, callOptions ...callopt.Option) (r *customer.UpdateQuickReplyResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateQuickReply(ctx, req)
}

func (p *kCustomerServiceClient) DeleteQuickReply(ctx context.Context, req *customer.DeleteQuickReplyReq, callOptions ...callopt.Option) (r *customer.DeleteQuickReplyResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteQuickReply(ctx, req)
}

func (p *kCustomerServiceClient) CreateConvCategory(ctx context.Context, req *customer.CreateConvCategoryReq, callOptions ...callopt.Option) (r *customer.CreateConvCategoryResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateConvCategory(ctx, req)
}

func (p *kCustomerServiceClient) ListConvCategory(ctx context.Context, req *customer.ListConvCategoryReq, callOptions ...callopt.Option) (r *customer.ListConvCategoryResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListConvCategory(ctx, req)
}

func (p *kCustomerServiceClient) UpdateConversationClassify(ctx context.Context, req *customer.UpdateConversationClassifyReq, callOptions ...callopt.Option) (r *customer.UpdateConversationClassifyResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateConversationClassify(ctx, req)
}

func (p *kCustomerServiceClient) CreateConvTag(ctx context.Context, req *customer.CreateConvTagReq, callOptions ...callopt.Option) (r *customer.CreateConvTagResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateConvTag(ctx, req)
}

func (p *kCustomerServiceClient) ListConvTag(ctx context.Context, req *customer.ListConvTagReq, callOptions ...callopt.Option) (r *customer.ListConvTagResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListConvTag(ctx, req)
}

func (p *kCustomerServiceClient) UpdateConvTag(ctx context.Context, req *customer.UpdateConvTagReq, callOptions ...callopt.Option) (r *customer.UpdateConvTagResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateConvTag(ctx, req)
}

func (p *kCustomerServiceClient) DeleteConvTag(ctx context.Context, req *customer.DeleteConvTagReq, callOptions ...callopt.Option) (r *customer.DeleteConvTagResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteConvTag(ctx, req)
}

func (p *kCustomerServiceClient) GetConversationStats(ctx context.Context, req *customer.GetConversationStatsReq, callOptions ...callopt.Option) (r *customer.GetConversationStatsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetConversationStats(ctx, req)
}

func (p *kCustomerServiceClient) GetConversationMonitor(ctx context.Context, req *customer.GetConversationMonitorReq, callOptions ...callopt.Option) (r *customer.GetConversationMonitorResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetConversationMonitor(ctx, req)
}

func (p *kCustomerServiceClient) ExportConversations(ctx context.Context, req *customer.ExportConversationsReq, callOptions ...callopt.Option) (r *customer.ExportConversationsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ExportConversations(ctx, req)
}

func (p *kCustomerServiceClient) MsgAutoClassify(ctx context.Context, req *customer.MsgAutoClassifyReq, callOptions ...callopt.Option) (r *customer.MsgAutoClassifyResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.MsgAutoClassify(ctx, req)
}

func (p *kCustomerServiceClient) AdjustMsgClassify(ctx context.Context, req *customer.AdjustMsgClassifyReq, callOptions ...callopt.Option) (r *customer.AdjustMsgClassifyResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AdjustMsgClassify(ctx, req)
}

func (p *kCustomerServiceClient) GetClassifyStats(ctx context.Context, req *customer.GetClassifyStatsReq, callOptions ...callopt.Option) (r *customer.GetClassifyStatsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetClassifyStats(ctx, req)
}

func (p *kCustomerServiceClient) CreateMsgCategory(ctx context.Context, req *customer.CreateMsgCategoryReq, callOptions ...callopt.Option) (r *customer.CreateMsgCategoryResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateMsgCategory(ctx, req)
}

func (p *kCustomerServiceClient) ListMsgCategory(ctx context.Context, req *customer.ListMsgCategoryReq, callOptions ...callopt.Option) (r *customer.ListMsgCategoryResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListMsgCategory(ctx, req)
}

func (p *kCustomerServiceClient) UpdateMsgCategory(ctx context.Context, req *customer.UpdateMsgCategoryReq, callOptions ...callopt.Option) (r *customer.UpdateMsgCategoryResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateMsgCategory(ctx, req)
}

func (p *kCustomerServiceClient) DeleteMsgCategory(ctx context.Context, req *customer.DeleteMsgCategoryReq, callOptions ...callopt.Option) (r *customer.DeleteMsgCategoryResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteMsgCategory(ctx, req)
}

func (p *kCustomerServiceClient) Login(ctx context.Context, req *customer.LoginReq, callOptions ...callopt.Option) (r *customer.LoginResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Login(ctx, req)
}

func (p *kCustomerServiceClient) GetCurrentUser(ctx context.Context, req *customer.GetCurrentUserReq, callOptions ...callopt.Option) (r *customer.GetCurrentUserResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetCurrentUser(ctx, req)
}

func (p *kCustomerServiceClient) Register(ctx context.Context, req *customer.RegisterReq, callOptions ...callopt.Option) (r *customer.RegisterResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Register(ctx, req)
}

func (p *kCustomerServiceClient) Logout(ctx context.Context, req *customer.LogoutReq, callOptions ...callopt.Option) (r *customer.LogoutResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Logout(ctx, req)
}

func (p *kCustomerServiceClient) EncryptMessage(ctx context.Context, req *customer.EncryptMessageReq, callOptions ...callopt.Option) (r *customer.EncryptMessageResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.EncryptMessage(ctx, req)
}

func (p *kCustomerServiceClient) DecryptMessage(ctx context.Context, req *customer.DecryptMessageReq, callOptions ...callopt.Option) (r *customer.DecryptMessageResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DecryptMessage(ctx, req)
}

func (p *kCustomerServiceClient) DesensitizeMessage(ctx context.Context, req *customer.DesensitizeMessageReq, callOptions ...callopt.Option) (r *customer.DesensitizeMessageResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DesensitizeMessage(ctx, req)
}

func (p *kCustomerServiceClient) ArchiveConversations(ctx context.Context, req *customer.ArchiveConversationsReq, callOptions ...callopt.Option) (r *customer.ArchiveConversationsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ArchiveConversations(ctx, req)
}

func (p *kCustomerServiceClient) GetArchiveTask(ctx context.Context, req *customer.GetArchiveTaskReq, callOptions ...callopt.Option) (r *customer.GetArchiveTaskResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetArchiveTask(ctx, req)
}

func (p *kCustomerServiceClient) QueryArchivedConversation(ctx context.Context, req *customer.QueryArchivedConversationReq, callOptions ...callopt.Option) (r *customer.QueryArchivedConversationResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.QueryArchivedConversation(ctx, req)
}
