// Code generated by Kitex v0.15.4. DO NOT EDIT.

package customerservice

import (
	"context"
	"errors"
	customer "example_shop/service/customer/kitex_gen/customer"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"GetCustomerService": kitex.NewMethodInfo(
		getCustomerServiceHandler,
		newCustomerServiceGetCustomerServiceArgs,
		newCustomerServiceGetCustomerServiceResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListCustomerService": kitex.NewMethodInfo(
		listCustomerServiceHandler,
		newCustomerServiceListCustomerServiceArgs,
		newCustomerServiceListCustomerServiceResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreateShiftConfig": kitex.NewMethodInfo(
		createShiftConfigHandler,
		newCustomerServiceCreateShiftConfigArgs,
		newCustomerServiceCreateShiftConfigResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListShiftConfig": kitex.NewMethodInfo(
		listShiftConfigHandler,
		newCustomerServiceListShiftConfigArgs,
		newCustomerServiceListShiftConfigResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateShiftConfig": kitex.NewMethodInfo(
		updateShiftConfigHandler,
		newCustomerServiceUpdateShiftConfigArgs,
		newCustomerServiceUpdateShiftConfigResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteShiftConfig": kitex.NewMethodInfo(
		deleteShiftConfigHandler,
		newCustomerServiceDeleteShiftConfigArgs,
		newCustomerServiceDeleteShiftConfigResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"AssignSchedule": kitex.NewMethodInfo(
		assignScheduleHandler,
		newCustomerServiceAssignScheduleArgs,
		newCustomerServiceAssignScheduleResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListScheduleGrid": kitex.NewMethodInfo(
		listScheduleGridHandler,
		newCustomerServiceListScheduleGridArgs,
		newCustomerServiceListScheduleGridResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpsertScheduleCell": kitex.NewMethodInfo(
		upsertScheduleCellHandler,
		newCustomerServiceUpsertScheduleCellArgs,
		newCustomerServiceUpsertScheduleCellResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"AutoSchedule": kitex.NewMethodInfo(
		autoScheduleHandler,
		newCustomerServiceAutoScheduleArgs,
		newCustomerServiceAutoScheduleResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"AssignCustomer": kitex.NewMethodInfo(
		assignCustomerHandler,
		newCustomerServiceAssignCustomerArgs,
		newCustomerServiceAssignCustomerResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreateConversation": kitex.NewMethodInfo(
		createConversationHandler,
		newCustomerServiceCreateConversationArgs,
		newCustomerServiceCreateConversationResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"EndConversation": kitex.NewMethodInfo(
		endConversationHandler,
		newCustomerServiceEndConversationArgs,
		newCustomerServiceEndConversationResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"TransferConversation": kitex.NewMethodInfo(
		transferConversationHandler,
		newCustomerServiceTransferConversationArgs,
		newCustomerServiceTransferConversationResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ApplyLeaveTransfer": kitex.NewMethodInfo(
		applyLeaveTransferHandler,
		newCustomerServiceApplyLeaveTransferArgs,
		newCustomerServiceApplyLeaveTransferResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ApproveLeaveTransfer": kitex.NewMethodInfo(
		approveLeaveTransferHandler,
		newCustomerServiceApproveLeaveTransferArgs,
		newCustomerServiceApproveLeaveTransferResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetLeaveTransfer": kitex.NewMethodInfo(
		getLeaveTransferHandler,
		newCustomerServiceGetLeaveTransferArgs,
		newCustomerServiceGetLeaveTransferResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListLeaveTransfer": kitex.NewMethodInfo(
		listLeaveTransferHandler,
		newCustomerServiceListLeaveTransferArgs,
		newCustomerServiceListLeaveTransferResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetLeaveAuditLog": kitex.NewMethodInfo(
		getLeaveAuditLogHandler,
		newCustomerServiceGetLeaveAuditLogArgs,
		newCustomerServiceGetLeaveAuditLogResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ApplyChainSwap": kitex.NewMethodInfo(
		applyChainSwapHandler,
		newCustomerServiceApplyChainSwapArgs,
		newCustomerServiceApplyChainSwapResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ApproveChainSwap": kitex.NewMethodInfo(
		approveChainSwapHandler,
		newCustomerServiceApproveChainSwapArgs,
		newCustomerServiceApproveChainSwapResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListChainSwap": kitex.NewMethodInfo(
		listChainSwapHandler,
		newCustomerServiceListChainSwapArgs,
		newCustomerServiceListChainSwapResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetChainSwap": kitex.NewMethodInfo(
		getChainSwapHandler,
		newCustomerServiceGetChainSwapArgs,
		newCustomerServiceGetChainSwapResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Heartbeat": kitex.NewMethodInfo(
		heartbeatHandler,
		newCustomerServiceHeartbeatArgs,
		newCustomerServiceHeartbeatResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListOnlineCustomers": kitex.NewMethodInfo(
		listOnlineCustomersHandler,
		newCustomerServiceListOnlineCustomersArgs,
		newCustomerServiceListOnlineCustomersResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetSwapCandidates": kitex.NewMethodInfo(
		getSwapCandidatesHandler,
		newCustomerServiceGetSwapCandidatesArgs,
		newCustomerServiceGetSwapCandidatesResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CheckSwapConflict": kitex.NewMethodInfo(
		checkSwapConflictHandler,
		newCustomerServiceCheckSwapConflictArgs,
		newCustomerServiceCheckSwapConflictResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListConversation": kitex.NewMethodInfo(
		listConversationHandler,
		newCustomerServiceListConversationArgs,
		newCustomerServiceListConversationResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListConversationHistory": kitex.NewMethodInfo(
		listConversationHistoryHandler,
		newCustomerServiceListConversationHistoryArgs,
		newCustomerServiceListConversationHistoryResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListConversationMessage": kitex.NewMethodInfo(
		listConversationMessageHandler,
		newCustomerServiceListConversationMessageArgs,
		newCustomerServiceListConversationMessageResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SendConversationMessage": kitex.NewMethodInfo(
		sendConversationMessageHandler,
		newCustomerServiceSendConversationMessageArgs,
		newCustomerServiceSendConversationMessageResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListQuickReply": kitex.NewMethodInfo(
		listQuickReplyHandler,
		newCustomerServiceListQuickReplyArgs,
		newCustomerServiceListQuickReplyResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreateQuickReply": kitex.NewMethodInfo(
		createQuickReplyHandler,
		newCustomerServiceCreateQuickReplyArgs,
		newCustomerServiceCreateQuickReplyResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateQuickReply": kitex.NewMethodInfo(
		updateQuickReplyHandler,
		newCustomerServiceUpdateQuickReplyArgs,
		newCustomerServiceUpdateQuickReplyResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteQuickReply": kitex.NewMethodInfo(
		deleteQuickReplyHandler,
		newCustomerServiceDeleteQuickReplyArgs,
		newCustomerServiceDeleteQuickReplyResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreateConvCategory": kitex.NewMethodInfo(
		createConvCategoryHandler,
		newCustomerServiceCreateConvCategoryArgs,
		newCustomerServiceCreateConvCategoryResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListConvCategory": kitex.NewMethodInfo(
		listConvCategoryHandler,
		newCustomerServiceListConvCategoryArgs,
		newCustomerServiceListConvCategoryResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateConversationClassify": kitex.NewMethodInfo(
		updateConversationClassifyHandler,
		newCustomerServiceUpdateConversationClassifyArgs,
		newCustomerServiceUpdateConversationClassifyResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreateConvTag": kitex.NewMethodInfo(
		createConvTagHandler,
		newCustomerServiceCreateConvTagArgs,
		newCustomerServiceCreateConvTagResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListConvTag": kitex.NewMethodInfo(
		listConvTagHandler,
		newCustomerServiceListConvTagArgs,
		newCustomerServiceListConvTagResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateConvTag": kitex.NewMethodInfo(
		updateConvTagHandler,
		newCustomerServiceUpdateConvTagArgs,
		newCustomerServiceUpdateConvTagResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteConvTag": kitex.NewMethodInfo(
		deleteConvTagHandler,
		newCustomerServiceDeleteConvTagArgs,
		newCustomerServiceDeleteConvTagResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetConversationStats": kitex.NewMethodInfo(
		getConversationStatsHandler,
		newCustomerServiceGetConversationStatsArgs,
		newCustomerServiceGetConversationStatsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetConversationMonitor": kitex.NewMethodInfo(
		getConversationMonitorHandler,
		newCustomerServiceGetConversationMonitorArgs,
		newCustomerServiceGetConversationMonitorResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ExportConversations": kitex.NewMethodInfo(
		exportConversationsHandler,
		newCustomerServiceExportConversationsArgs,
		newCustomerServiceExportConversationsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"MsgAutoClassify": kitex.NewMethodInfo(
		msgAutoClassifyHandler,
		newCustomerServiceMsgAutoClassifyArgs,
		newCustomerServiceMsgAutoClassifyResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"AdjustMsgClassify": kitex.NewMethodInfo(
		adjustMsgClassifyHandler,
		newCustomerServiceAdjustMsgClassifyArgs,
		newCustomerServiceAdjustMsgClassifyResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetClassifyStats": kitex.NewMethodInfo(
		getClassifyStatsHandler,
		newCustomerServiceGetClassifyStatsArgs,
		newCustomerServiceGetClassifyStatsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreateMsgCategory": kitex.NewMethodInfo(
		createMsgCategoryHandler,
		newCustomerServiceCreateMsgCategoryArgs,
		newCustomerServiceCreateMsgCategoryResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListMsgCategory": kitex.NewMethodInfo(
		listMsgCategoryHandler,
		newCustomerServiceListMsgCategoryArgs,
		newCustomerServiceListMsgCategoryResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateMsgCategory": kitex.NewMethodInfo(
		updateMsgCategoryHandler,
		newCustomerServiceUpdateMsgCategoryArgs,
		newCustomerServiceUpdateMsgCategoryResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteMsgCategory": kitex.NewMethodInfo(
		deleteMsgCategoryHandler,
		newCustomerServiceDeleteMsgCategoryArgs,
		newCustomerServiceDeleteMsgCategoryResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Login": kitex.NewMethodInfo(
		loginHandler,
		newCustomerServiceLoginArgs,
		newCustomerServiceLoginResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetCurrentUser": kitex.NewMethodInfo(
		getCurrentUserHandler,
		newCustomerServiceGetCurrentUserArgs,
		newCustomerServiceGetCurrentUserResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Register": kitex.NewMethodInfo(
		registerHandler,
		newCustomerServiceRegisterArgs,
		newCustomerServiceRegisterResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Logout": kitex.NewMethodInfo(
		logoutHandler,
		newCustomerServiceLogoutArgs,
		newCustomerServiceLogoutResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"EncryptMessage": kitex.NewMethodInfo(
		encryptMessageHandler,
		newCustomerServiceEncryptMessageArgs,
		newCustomerServiceEncryptMessageResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DecryptMessage": kitex.NewMethodInfo(
		decryptMessageHandler,
		newCustomerServiceDecryptMessageArgs,
		newCustomerServiceDecryptMessageResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DesensitizeMessage": kitex.NewMethodInfo(
		desensitizeMessageHandler,
		newCustomerServiceDesensitizeMessageArgs,
		newCustomerServiceDesensitizeMessageResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ArchiveConversations": kitex.NewMethodInfo(
		archiveConversationsHandler,
		newCustomerServiceArchiveConversationsArgs,
		newCustomerServiceArchiveConversationsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetArchiveTask": kitex.NewMethodInfo(
		getArchiveTaskHandler,
		newCustomerServiceGetArchiveTaskArgs,
		newCustomerServiceGetArchiveTaskResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"QueryArchivedConversation": kitex.NewMethodInfo(
		queryArchivedConversationHandler,
		newCustomerServiceQueryArchivedConversationArgs,
		newCustomerServiceQueryArchivedConversationResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	customerServiceServiceInfo                = NewServiceInfo()
	customerServiceServiceInfoForClient       = NewServiceInfoForClient()
	customerServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return customerServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return customerServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return customerServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "CustomerService"
	handlerType := (*customer.CustomerService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "customer",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.15.4",
		Extra:           extra,
	}
	return svcInfo
}

func getCustomerServiceHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*customer.CustomerServiceGetCustomerServiceArgs)
	realResult := result.(*customer.CustomerServiceGetCustomerServiceResult)
	success, err := handler.(customer.CustomerService).GetCustomerService(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCustomerServiceGetCustomerServiceArgs() interface{} {
	return customer.NewCustomerServiceGetCustomerServiceArgs()
}

func newCustomerServiceGetCustomerServiceResult() interface{} {
	return customer.NewCustomerServiceGetCustomerServiceResult()
}

func listCustomerServiceHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*customer.CustomerServiceListCustomerServiceArgs)
	realResult := result.(*customer.CustomerServiceListCustomerServiceResult)
	success, err := handler.(customer.CustomerService).ListCustomerService(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCustomerServiceListCustomerServiceArgs() interface{} {
	return customer.NewCustomerServiceListCustomerServiceArgs()
}

func newCustomerServiceListCustomerServiceResult() interface{} {
	return customer.NewCustomerServiceListCustomerServiceResult()
}

func createShiftConfigHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*customer.CustomerServiceCreateShiftConfigArgs)
	realResult := result.(*customer.CustomerServiceCreateShiftConfigResult)
	success, err := handler.(customer.CustomerService).CreateShiftConfig(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCustomerServiceCreateShiftConfigArgs() interface{} {
	return customer.NewCustomerServiceCreateShiftConfigArgs()
}

func newCustomerServiceCreateShiftConfigResult() interface{} {
	return customer.NewCustomerServiceCreateShiftConfigResult()
}

func listShiftConfigHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*customer.CustomerServiceListShiftConfigArgs)
	realResult := result.(*customer.CustomerServiceListShiftConfigResult)
	success, err := handler.(customer.CustomerService).ListShiftConfig(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCustomerServiceListShiftConfigArgs() interface{} {
	return customer.NewCustomerServiceListShiftConfigArgs()
}

func newCustomerServiceListShiftConfigResult() interface{} {
	return customer.NewCustomerServiceListShiftConfigResult()
}

func updateShiftConfigHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*customer.CustomerServiceUpdateShiftConfigArgs)
	realResult := result.(*customer.CustomerServiceUpdateShiftConfigResult)
	success, err := handler.(customer.CustomerService).UpdateShiftConfig(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCustomerServiceUpdateShiftConfigArgs() interface{} {
	return customer.NewCustomerServiceUpdateShiftConfigArgs()
}

func newCustomerServiceUpdateShiftConfigResult() interface{} {
	return customer.NewCustomerServiceUpdateShiftConfigResult()
}

func deleteShiftConfigHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*customer.CustomerServiceDeleteShiftConfigArgs)
	realResult := result.(*customer.CustomerServiceDeleteShiftConfigResult)
	success, err := handler.(customer.CustomerService).DeleteShiftConfig(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCustomerServiceDeleteShiftConfigArgs() interface{} {
	return customer.NewCustomerServiceDeleteShiftConfigArgs()
}

func newCustomerServiceDeleteShiftConfigResult() interface{} {
	return customer.NewCustomerServiceDeleteShiftConfigResult()
}

func assignScheduleHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*customer.CustomerServiceAssignScheduleArgs)
	realResult := result.(*customer.CustomerServiceAssignScheduleResult)
	success, err := handler.(customer.CustomerService).AssignSchedule(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCustomerServiceAssignScheduleArgs() interface{} {
	return customer.NewCustomerServiceAssignScheduleArgs()
}

func newCustomerServiceAssignScheduleResult() interface{} {
	return customer.NewCustomerServiceAssignScheduleResult()
}

func listScheduleGridHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*customer.CustomerServiceListScheduleGridArgs)
	realResult := result.(*customer.CustomerServiceListScheduleGridResult)
	success, err := handler.(customer.CustomerService).ListScheduleGrid(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCustomerServiceListScheduleGridArgs() interface{} {
	return customer.NewCustomerServiceListScheduleGridArgs()
}

func newCustomerServiceListScheduleGridResult() interface{} {
	return customer.NewCustomerServiceListScheduleGridResult()
}

func upsertScheduleCellHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*customer.CustomerServiceUpsertScheduleCellArgs)
	realResult := result.(*customer.CustomerServiceUpsertScheduleCellResult)
	success, err := handler.(customer.CustomerService).UpsertScheduleCell(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCustomerServiceUpsertScheduleCellArgs() interface{} {
	return customer.NewCustomerServiceUpsertScheduleCellArgs()
}

func newCustomerServiceUpsertScheduleCellResult() interface{} {
	return customer.NewCustomerServiceUpsertScheduleCellResult()
}

func autoScheduleHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*customer.CustomerServiceAutoScheduleArgs)
	realResult := result.(*customer.CustomerServiceAutoScheduleResult)
	success, err := handler.(customer.CustomerService).AutoSchedule(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCustomerServiceAutoScheduleArgs() interface{} {
	return customer.NewCustomerServiceAutoScheduleArgs()
}

func newCustomerServiceAutoScheduleResult() interface{} {
	return customer.NewCustomerServiceAutoScheduleResult()
}

func assignCustomerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*customer.CustomerServiceAssignCustomerArgs)
	realResult := result.(*customer.CustomerServiceAssignCustomerResult)
	success, err := handler.(customer.CustomerService).AssignCustomer(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCustomerServiceAssignCustomerArgs() interface{} {
	return customer.NewCustomerServiceAssignCustomerArgs()
}

func newCustomerServiceAssignCustomerResult() interface{} {
	return customer.NewCustomerServiceAssignCustomerResult()
}

func createConversationHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*customer.CustomerServiceCreateConversationArgs)
	realResult := result.(*customer.CustomerServiceCreateConversationResult)
	success, err := handler.(customer.CustomerService).CreateConversation(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCustomerServiceCreateConversationArgs() interface{} {
	return customer.NewCustomerServiceCreateConversationArgs()
}

func newCustomerServiceCreateConversationResult() interface{} {
	return customer.NewCustomerServiceCreateConversationResult()
}

func endConversationHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*customer.CustomerServiceEndConversationArgs)
	realResult := result.(*customer.CustomerServiceEndConversationResult)
	success, err := handler.(customer.CustomerService).EndConversation(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCustomerServiceEndConversationArgs() interface{} {
	return customer.NewCustomerServiceEndConversationArgs()
}

func newCustomerServiceEndConversationResult() interface{} {
	return customer.NewCustomerServiceEndConversationResult()
}

func transferConversationHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*customer.CustomerServiceTransferConversationArgs)
	realResult := result.(*customer.CustomerServiceTransferConversationResult)
	success, err := handler.(customer.CustomerService).TransferConversation(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCustomerServiceTransferConversationArgs() interface{} {
	return customer.NewCustomerServiceTransferConversationArgs()
}

func newCustomerServiceTransferConversationResult() interface{} {
	return customer.NewCustomerServiceTransferConversationResult()
}

func applyLeaveTransferHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*customer.CustomerServiceApplyLeaveTransferArgs)
	realResult := result.(*customer.CustomerServiceApplyLeaveTransferResult)
	success, err := handler.(customer.CustomerService).ApplyLeaveTransfer(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCustomerServiceApplyLeaveTransferArgs() interface{} {
	return customer.NewCustomerServiceApplyLeaveTransferArgs()
}

func newCustomerServiceApplyLeaveTransferResult() interface{} {
	return customer.NewCustomerServiceApplyLeaveTransferResult()
}

func approveLeaveTransferHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*customer.CustomerServiceApproveLeaveTransferArgs)
	realResult := result.(*customer.CustomerServiceApproveLeaveTransferResult)
	success, err := handler.(customer.CustomerService).ApproveLeaveTransfer(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCustomerServiceApproveLeaveTransferArgs() interface{} {
	return customer.NewCustomerServiceApproveLeaveTransferArgs()
}

func newCustomerServiceApproveLeaveTransferResult() interface{} {
	return customer.NewCustomerServiceApproveLeaveTransferResult()
}

func getLeaveTransferHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*customer.CustomerServiceGetLeaveTransferArgs)
	realResult := result.(*customer.CustomerServiceGetLeaveTransferResult)
	success, err := handler.(customer.CustomerService).GetLeaveTransfer(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCustomerServiceGetLeaveTransferArgs() interface{} {
	return customer.NewCustomerServiceGetLeaveTransferArgs()
}

func newCustomerServiceGetLeaveTransferResult() interface{} {
	return customer.NewCustomerServiceGetLeaveTransferResult()
}

func listLeaveTransferHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*customer.CustomerServiceListLeaveTransferArgs)
	realResult := result.(*customer.CustomerServiceListLeaveTransferResult)
	success, err := handler.(customer.CustomerService).ListLeaveTransfer(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCustomerServiceListLeaveTransferArgs() interface{} {
	return customer.NewCustomerServiceListLeaveTransferArgs()
}

func newCustomerServiceListLeaveTransferResult() interface{} {
	return customer.NewCustomerServiceListLeaveTransferResult()
}

func getLeaveAuditLogHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*customer.CustomerServiceGetLeaveAuditLogArgs)
	realResult := result.(*customer.CustomerServiceGetLeaveAuditLogResult)
	success, err := handler.(customer.CustomerService).GetLeaveAuditLog(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCustomerServiceGetLeaveAuditLogArgs() interface{} {
	return customer.NewCustomerServiceGetLeaveAuditLogArgs()
}

func newCustomerServiceGetLeaveAuditLogResult() interface{} {
	return customer.NewCustomerServiceGetLeaveAuditLogResult()
}

func applyChainSwapHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*customer.CustomerServiceApplyChainSwapArgs)
	realResult := result.(*customer.CustomerServiceApplyChainSwapResult)
	success, err := handler.(customer.CustomerService).ApplyChainSwap(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCustomerServiceApplyChainSwapArgs() interface{} {
	return customer.NewCustomerServiceApplyChainSwapArgs()
}

func newCustomerServiceApplyChainSwapResult() interface{} {
	return customer.NewCustomerServiceApplyChainSwapResult()
}

func approveChainSwapHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*customer.CustomerServiceApproveChainSwapArgs)
	realResult := result.(*customer.CustomerServiceApproveChainSwapResult)
	success, err := handler.(customer.CustomerService).ApproveChainSwap(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCustomerServiceApproveChainSwapArgs() interface{} {
	return customer.NewCustomerServiceApproveChainSwapArgs()
}

func newCustomerServiceApproveChainSwapResult() interface{} {
	return customer.NewCustomerServiceApproveChainSwapResult()
}

func listChainSwapHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*customer.CustomerServiceListChainSwapArgs)
	realResult := result.(*customer.CustomerServiceListChainSwapResult)
	success, err := handler.(customer.CustomerService).ListChainSwap(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCustomerServiceListChainSwapArgs() interface{} {
	return customer.NewCustomerServiceListChainSwapArgs()
}

func newCustomerServiceListChainSwapResult() interface{} {
	return customer.NewCustomerServiceListChainSwapResult()
}

func getChainSwapHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*customer.CustomerServiceGetChainSwapArgs)
	realResult := result.(*customer.CustomerServiceGetChainSwapResult)
	success, err := handler.(customer.CustomerService).GetChainSwap(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCustomerServiceGetChainSwapArgs() interface{} {
	return customer.NewCustomerServiceGetChainSwapArgs()
}

func newCustomerServiceGetChainSwapResult() interface{} {
	return customer.NewCustomerServiceGetChainSwapResult()
}

func heartbeatHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*customer.CustomerServiceHeartbeatArgs)
	realResult := result.(*customer.CustomerServiceHeartbeatResult)
	success, err := handler.(customer.CustomerService).Heartbeat(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCustomerServiceHeartbeatArgs() interface{} {
	return customer.NewCustomerServiceHeartbeatArgs()
}

func newCustomerServiceHeartbeatResult() interface{} {
	return customer.NewCustomerServiceHeartbeatResult()
}

func listOnlineCustomersHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*customer.CustomerServiceListOnlineCustomersArgs)
	realResult := result.(*customer.CustomerServiceListOnlineCustomersResult)
	success, err := handler.(customer.CustomerService).ListOnlineCustomers(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCustomerServiceListOnlineCustomersArgs() interface{} {
	return customer.NewCustomerServiceListOnlineCustomersArgs()
}

func newCustomerServiceListOnlineCustomersResult() interface{} {
	return customer.NewCustomerServiceListOnlineCustomersResult()
}

func getSwapCandidatesHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*customer.CustomerServiceGetSwapCandidatesArgs)
	realResult := result.(*customer.CustomerServiceGetSwapCandidatesResult)
	success, err := handler.(customer.CustomerService).GetSwapCandidates(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCustomerServiceGetSwapCandidatesArgs() interface{} {
	return customer.NewCustomerServiceGetSwapCandidatesArgs()
}

func newCustomerServiceGetSwapCandidatesResult() interface{} {
	return customer.NewCustomerServiceGetSwapCandidatesResult()
}

func checkSwapConflictHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*customer.CustomerServiceCheckSwapConflictArgs)
	realResult := result.(*customer.CustomerServiceCheckSwapConflictResult)
	success, err := handler.(customer.CustomerService).CheckSwapConflict(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCustomerServiceCheckSwapConflictArgs() interface{} {
	return customer.NewCustomerServiceCheckSwapConflictArgs()
}

func newCustomerServiceCheckSwapConflictResult() interface{} {
	return customer.NewCustomerServiceCheckSwapConflictResult()
}

func listConversationHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*customer.CustomerServiceListConversationArgs)
	realResult := result.(*customer.CustomerServiceListConversationResult)
	success, err := handler.(customer.CustomerService).ListConversation(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCustomerServiceListConversationArgs() interface{} {
	return customer.NewCustomerServiceListConversationArgs()
}

func newCustomerServiceListConversationResult() interface{} {
	return customer.NewCustomerServiceListConversationResult()
}

func listConversationHistoryHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*customer.CustomerServiceListConversationHistoryArgs)
	realResult := result.(*customer.CustomerServiceListConversationHistoryResult)
	success, err := handler.(customer.CustomerService).ListConversationHistory(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCustomerServiceListConversationHistoryArgs() interface{} {
	return customer.NewCustomerServiceListConversationHistoryArgs()
}

func newCustomerServiceListConversationHistoryResult() interface{} {
	return customer.NewCustomerServiceListConversationHistoryResult()
}

func listConversationMessageHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*customer.CustomerServiceListConversationMessageArgs)
	realResult := result.(*customer.CustomerServiceListConversationMessageResult)
	success, err := handler.(customer.CustomerService).ListConversationMessage(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCustomerServiceListConversationMessageArgs() interface{} {
	return customer.NewCustomerServiceListConversationMessageArgs()
}

func newCustomerServiceListConversationMessageResult() interface{} {
	return customer.NewCustomerServiceListConversationMessageResult()
}

func sendConversationMessageHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*customer.CustomerServiceSendConversationMessageArgs)
	realResult := result.(*customer.CustomerServiceSendConversationMessageResult)
	success, err := handler.(customer.CustomerService).SendConversationMessage(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCustomerServiceSendConversationMessageArgs() interface{} {
	return customer.NewCustomerServiceSendConversationMessageArgs()
}

func newCustomerServiceSendConversationMessageResult() interface{} {
	return customer.NewCustomerServiceSendConversationMessageResult()
}

func listQuickReplyHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*customer.CustomerServiceListQuickReplyArgs)
	realResult := result.(*customer.CustomerServiceListQuickReplyResult)
	success, err := handler.(customer.CustomerService).ListQuickReply(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCustomerServiceListQuickReplyArgs() interface{} {
	return customer.NewCustomerServiceListQuickReplyArgs()
}

func newCustomerServiceListQuickReplyResult() interface{} {
	return customer.NewCustomerServiceListQuickReplyResult()
}

func createQuickReplyHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*customer.CustomerServiceCreateQuickReplyArgs)
	realResult := result.(*customer.CustomerServiceCreateQuickReplyResult)
	success, err := handler.(customer.CustomerService).CreateQuickReply(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCustomerServiceCreateQuickReplyArgs() interface{} {
	return customer.NewCustomerServiceCreateQuickReplyArgs()
}

func newCustomerServiceCreateQuickReplyResult() interface{} {
	return customer.NewCustomerServiceCreateQuickReplyResult()
}

func updateQuickReplyHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*customer.CustomerServiceUpdateQuickReplyArgs)
	realResult := result.(*customer.CustomerServiceUpdateQuickReplyResult)
	success, err := handler.(customer.CustomerService).UpdateQuickReply(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCustomerServiceUpdateQuickReplyArgs() interface{} {
	return customer.NewCustomerServiceUpdateQuickReplyArgs()
}

func newCustomerServiceUpdateQuickReplyResult() interface{} {
	return customer.NewCustomerServiceUpdateQuickReplyResult()
}

func deleteQuickReplyHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*customer.CustomerServiceDeleteQuickReplyArgs)
	realResult := result.(*customer.CustomerServiceDeleteQuickReplyResult)
	success, err := handler.(customer.CustomerService).DeleteQuickReply(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCustomerServiceDeleteQuickReplyArgs() interface{} {
	return customer.NewCustomerServiceDeleteQuickReplyArgs()
}

func newCustomerServiceDeleteQuickReplyResult() interface{} {
	return customer.NewCustomerServiceDeleteQuickReplyResult()
}

func createConvCategoryHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*customer.CustomerServiceCreateConvCategoryArgs)
	realResult := result.(*customer.CustomerServiceCreateConvCategoryResult)
	success, err := handler.(customer.CustomerService).CreateConvCategory(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCustomerServiceCreateConvCategoryArgs() interface{} {
	return customer.NewCustomerServiceCreateConvCategoryArgs()
}

func newCustomerServiceCreateConvCategoryResult() interface{} {
	return customer.NewCustomerServiceCreateConvCategoryResult()
}

func listConvCategoryHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*customer.CustomerServiceListConvCategoryArgs)
	realResult := result.(*customer.CustomerServiceListConvCategoryResult)
	success, err := handler.(customer.CustomerService).ListConvCategory(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCustomerServiceListConvCategoryArgs() interface{} {
	return customer.NewCustomerServiceListConvCategoryArgs()
}

func newCustomerServiceListConvCategoryResult() interface{} {
	return customer.NewCustomerServiceListConvCategoryResult()
}

func updateConversationClassifyHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*customer.CustomerServiceUpdateConversationClassifyArgs)
	realResult := result.(*customer.CustomerServiceUpdateConversationClassifyResult)
	success, err := handler.(customer.CustomerService).UpdateConversationClassify(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCustomerServiceUpdateConversationClassifyArgs() interface{} {
	return customer.NewCustomerServiceUpdateConversationClassifyArgs()
}

func newCustomerServiceUpdateConversationClassifyResult() interface{} {
	return customer.NewCustomerServiceUpdateConversationClassifyResult()
}

func createConvTagHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*customer.CustomerServiceCreateConvTagArgs)
	realResult := result.(*customer.CustomerServiceCreateConvTagResult)
	success, err := handler.(customer.CustomerService).CreateConvTag(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCustomerServiceCreateConvTagArgs() interface{} {
	return customer.NewCustomerServiceCreateConvTagArgs()
}

func newCustomerServiceCreateConvTagResult() interface{} {
	return customer.NewCustomerServiceCreateConvTagResult()
}

func listConvTagHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*customer.CustomerServiceListConvTagArgs)
	realResult := result.(*customer.CustomerServiceListConvTagResult)
	success, err := handler.(customer.CustomerService).ListConvTag(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCustomerServiceListConvTagArgs() interface{} {
	return customer.NewCustomerServiceListConvTagArgs()
}

func newCustomerServiceListConvTagResult() interface{} {
	return customer.NewCustomerServiceListConvTagResult()
}

func updateConvTagHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*customer.CustomerServiceUpdateConvTagArgs)
	realResult := result.(*customer.CustomerServiceUpdateConvTagResult)
	success, err := handler.(customer.CustomerService).UpdateConvTag(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCustomerServiceUpdateConvTagArgs() interface{} {
	return customer.NewCustomerServiceUpdateConvTagArgs()
}

func newCustomerServiceUpdateConvTagResult() interface{} {
	return customer.NewCustomerServiceUpdateConvTagResult()
}

func deleteConvTagHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*customer.CustomerServiceDeleteConvTagArgs)
	realResult := result.(*customer.CustomerServiceDeleteConvTagResult)
	success, err := handler.(customer.CustomerService).DeleteConvTag(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCustomerServiceDeleteConvTagArgs() interface{} {
	return customer.NewCustomerServiceDeleteConvTagArgs()
}

func newCustomerServiceDeleteConvTagResult() interface{} {
	return customer.NewCustomerServiceDeleteConvTagResult()
}

func getConversationStatsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*customer.CustomerServiceGetConversationStatsArgs)
	realResult := result.(*customer.CustomerServiceGetConversationStatsResult)
	success, err := handler.(customer.CustomerService).GetConversationStats(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCustomerServiceGetConversationStatsArgs() interface{} {
	return customer.NewCustomerServiceGetConversationStatsArgs()
}

func newCustomerServiceGetConversationStatsResult() interface{} {
	return customer.NewCustomerServiceGetConversationStatsResult()
}

func getConversationMonitorHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*customer.CustomerServiceGetConversationMonitorArgs)
	realResult := result.(*customer.CustomerServiceGetConversationMonitorResult)
	success, err := handler.(customer.CustomerService).GetConversationMonitor(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCustomerServiceGetConversationMonitorArgs() interface{} {
	return customer.NewCustomerServiceGetConversationMonitorArgs()
}

func newCustomerServiceGetConversationMonitorResult() interface{} {
	return customer.NewCustomerServiceGetConversationMonitorResult()
}

func exportConversationsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*customer.CustomerServiceExportConversationsArgs)
	realResult := result.(*customer.CustomerServiceExportConversationsResult)
	success, err := handler.(customer.CustomerService).ExportConversations(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCustomerServiceExportConversationsArgs() interface{} {
	return customer.NewCustomerServiceExportConversationsArgs()
}

func newCustomerServiceExportConversationsResult() interface{} {
	return customer.NewCustomerServiceExportConversationsResult()
}

func msgAutoClassifyHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*customer.CustomerServiceMsgAutoClassifyArgs)
	realResult := result.(*customer.CustomerServiceMsgAutoClassifyResult)
	success, err := handler.(customer.CustomerService).MsgAutoClassify(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCustomerServiceMsgAutoClassifyArgs() interface{} {
	return customer.NewCustomerServiceMsgAutoClassifyArgs()
}

func newCustomerServiceMsgAutoClassifyResult() interface{} {
	return customer.NewCustomerServiceMsgAutoClassifyResult()
}

func adjustMsgClassifyHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*customer.CustomerServiceAdjustMsgClassifyArgs)
	realResult := result.(*customer.CustomerServiceAdjustMsgClassifyResult)
	success, err := handler.(customer.CustomerService).AdjustMsgClassify(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCustomerServiceAdjustMsgClassifyArgs() interface{} {
	return customer.NewCustomerServiceAdjustMsgClassifyArgs()
}

func newCustomerServiceAdjustMsgClassifyResult() interface{} {
	return customer.NewCustomerServiceAdjustMsgClassifyResult()
}

func getClassifyStatsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*customer.CustomerServiceGetClassifyStatsArgs)
	realResult := result.(*customer.CustomerServiceGetClassifyStatsResult)
	success, err := handler.(customer.CustomerService).GetClassifyStats(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCustomerServiceGetClassifyStatsArgs() interface{} {
	return customer.NewCustomerServiceGetClassifyStatsArgs()
}

func newCustomerServiceGetClassifyStatsResult() interface{} {
	return customer.NewCustomerServiceGetClassifyStatsResult()
}

func createMsgCategoryHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*customer.CustomerServiceCreateMsgCategoryArgs)
	realResult := result.(*customer.CustomerServiceCreateMsgCategoryResult)
	success, err := handler.(customer.CustomerService).CreateMsgCategory(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCustomerServiceCreateMsgCategoryArgs() interface{} {
	return customer.NewCustomerServiceCreateMsgCategoryArgs()
}

func newCustomerServiceCreateMsgCategoryResult() interface{} {
	return customer.NewCustomerServiceCreateMsgCategoryResult()
}

func listMsgCategoryHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*customer.CustomerServiceListMsgCategoryArgs)
	realResult := result.(*customer.CustomerServiceListMsgCategoryResult)
	success, err := handler.(customer.CustomerService).ListMsgCategory(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCustomerServiceListMsgCategoryArgs() interface{} {
	return customer.NewCustomerServiceListMsgCategoryArgs()
}

func newCustomerServiceListMsgCategoryResult() interface{} {
	return customer.NewCustomerServiceListMsgCategoryResult()
}

func updateMsgCategoryHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*customer.CustomerServiceUpdateMsgCategoryArgs)
	realResult := result.(*customer.CustomerServiceUpdateMsgCategoryResult)
	success, err := handler.(customer.CustomerService).UpdateMsgCategory(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCustomerServiceUpdateMsgCategoryArgs() interface{} {
	return customer.NewCustomerServiceUpdateMsgCategoryArgs()
}

func newCustomerServiceUpdateMsgCategoryResult() interface{} {
	return customer.NewCustomerServiceUpdateMsgCategoryResult()
}

func deleteMsgCategoryHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*customer.CustomerServiceDeleteMsgCategoryArgs)
	realResult := result.(*customer.CustomerServiceDeleteMsgCategoryResult)
	success, err := handler.(customer.CustomerService).DeleteMsgCategory(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCustomerServiceDeleteMsgCategoryArgs() interface{} {
	return customer.NewCustomerServiceDeleteMsgCategoryArgs()
}

func newCustomerServiceDeleteMsgCategoryResult() interface{} {
	return customer.NewCustomerServiceDeleteMsgCategoryResult()
}

func loginHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*customer.CustomerServiceLoginArgs)
	realResult := result.(*customer.CustomerServiceLoginResult)
	success, err := handler.(customer.CustomerService).Login(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCustomerServiceLoginArgs() interface{} {
	return customer.NewCustomerServiceLoginArgs()
}

func newCustomerServiceLoginResult() interface{} {
	return customer.NewCustomerServiceLoginResult()
}

func getCurrentUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*customer.CustomerServiceGetCurrentUserArgs)
	realResult := result.(*customer.CustomerServiceGetCurrentUserResult)
	success, err := handler.(customer.CustomerService).GetCurrentUser(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCustomerServiceGetCurrentUserArgs() interface{} {
	return customer.NewCustomerServiceGetCurrentUserArgs()
}

func newCustomerServiceGetCurrentUserResult() interface{} {
	return customer.NewCustomerServiceGetCurrentUserResult()
}

func registerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*customer.CustomerServiceRegisterArgs)
	realResult := result.(*customer.CustomerServiceRegisterResult)
	success, err := handler.(customer.CustomerService).Register(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCustomerServiceRegisterArgs() interface{} {
	return customer.NewCustomerServiceRegisterArgs()
}

func newCustomerServiceRegisterResult() interface{} {
	return customer.NewCustomerServiceRegisterResult()
}

func logoutHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*customer.CustomerServiceLogoutArgs)
	realResult := result.(*customer.CustomerServiceLogoutResult)
	success, err := handler.(customer.CustomerService).Logout(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCustomerServiceLogoutArgs() interface{} {
	return customer.NewCustomerServiceLogoutArgs()
}

func newCustomerServiceLogoutResult() interface{} {
	return customer.NewCustomerServiceLogoutResult()
}

func encryptMessageHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*customer.CustomerServiceEncryptMessageArgs)
	realResult := result.(*customer.CustomerServiceEncryptMessageResult)
	success, err := handler.(customer.CustomerService).EncryptMessage(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCustomerServiceEncryptMessageArgs() interface{} {
	return customer.NewCustomerServiceEncryptMessageArgs()
}

func newCustomerServiceEncryptMessageResult() interface{} {
	return customer.NewCustomerServiceEncryptMessageResult()
}

func decryptMessageHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*customer.CustomerServiceDecryptMessageArgs)
	realResult := result.(*customer.CustomerServiceDecryptMessageResult)
	success, err := handler.(customer.CustomerService).DecryptMessage(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCustomerServiceDecryptMessageArgs() interface{} {
	return customer.NewCustomerServiceDecryptMessageArgs()
}

func newCustomerServiceDecryptMessageResult() interface{} {
	return customer.NewCustomerServiceDecryptMessageResult()
}

func desensitizeMessageHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*customer.CustomerServiceDesensitizeMessageArgs)
	realResult := result.(*customer.CustomerServiceDesensitizeMessageResult)
	success, err := handler.(customer.CustomerService).DesensitizeMessage(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCustomerServiceDesensitizeMessageArgs() interface{} {
	return customer.NewCustomerServiceDesensitizeMessageArgs()
}

func newCustomerServiceDesensitizeMessageResult() interface{} {
	return customer.NewCustomerServiceDesensitizeMessageResult()
}

func archiveConversationsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*customer.CustomerServiceArchiveConversationsArgs)
	realResult := result.(*customer.CustomerServiceArchiveConversationsResult)
	success, err := handler.(customer.CustomerService).ArchiveConversations(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCustomerServiceArchiveConversationsArgs() interface{} {
	return customer.NewCustomerServiceArchiveConversationsArgs()
}

func newCustomerServiceArchiveConversationsResult() interface{} {
	return customer.NewCustomerServiceArchiveConversationsResult()
}

func getArchiveTaskHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*customer.CustomerServiceGetArchiveTaskArgs)
	realResult := result.(*customer.CustomerServiceGetArchiveTaskResult)
	success, err := handler.(customer.CustomerService).GetArchiveTask(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCustomerServiceGetArchiveTaskArgs() interface{} {
	return customer.NewCustomerServiceGetArchiveTaskArgs()
}

func newCustomerServiceGetArchiveTaskResult() interface{} {
	return customer.NewCustomerServiceGetArchiveTaskResult()
}

func queryArchivedConversationHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*customer.CustomerServiceQueryArchivedConversationArgs)
	realResult := result.(*customer.CustomerServiceQueryArchivedConversationResult)
	success, err := handler.(customer.CustomerService).QueryArchivedConversation(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCustomerServiceQueryArchivedConversationArgs() interface{} {
	return customer.NewCustomerServiceQueryArchivedConversationArgs()
}

func newCustomerServiceQueryArchivedConversationResult() interface{} {
	return customer.NewCustomerServiceQueryArchivedConversationResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetCustomerService(ctx context.Context, req *customer.GetCustomerServiceReq) (r *customer.GetCustomerServiceResp, err error) {
	var _args customer.CustomerServiceGetCustomerServiceArgs
	_args.Req = req
	var _result customer.CustomerServiceGetCustomerServiceResult
	if err = p.c.Call(ctx, "GetCustomerService", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListCustomerService(ctx context.Context, req *customer.ListCustomerServiceReq) (r *customer.ListCustomerServiceResp, err error) {
	var _args customer.CustomerServiceListCustomerServiceArgs
	_args.Req = req
	var _result customer.CustomerServiceListCustomerServiceResult
	if err = p.c.Call(ctx, "ListCustomerService", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateShiftConfig(ctx context.Context, req *customer.CreateShiftConfigReq) (r *customer.CreateShiftConfigResp, err error) {
	var _args customer.CustomerServiceCreateShiftConfigArgs
	_args.Req = req
	var _result customer.CustomerServiceCreateShiftConfigResult
	if err = p.c.Call(ctx, "CreateShiftConfig", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListShiftConfig(ctx context.Context, req *customer.ListShiftConfigReq) (r *customer.ListShiftConfigResp, err error) {
	var _args customer.CustomerServiceListShiftConfigArgs
	_args.Req = req
	var _result customer.CustomerServiceListShiftConfigResult
	if err = p.c.Call(ctx, "ListShiftConfig", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateShiftConfig(ctx context.Context, req *customer.UpdateShiftConfigReq) (r *customer.UpdateShiftConfigResp, err error) {
	var _args customer.CustomerServiceUpdateShiftConfigArgs
	_args.Req = req
	var _result customer.CustomerServiceUpdateShiftConfigResult
	if err = p.c.Call(ctx, "UpdateShiftConfig", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteShiftConfig(ctx context.Context, req *customer.DeleteShiftConfigReq) (r *customer.DeleteShiftConfigResp, err error) {
	var _args customer.CustomerServiceDeleteShiftConfigArgs
	_args.Req = req
	var _result customer.CustomerServiceDeleteShiftConfigResult
	if err = p.c.Call(ctx, "DeleteShiftConfig", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AssignSchedule(ctx context.Context, req *customer.AssignScheduleReq) (r *customer.AssignScheduleResp, err error) {
	var _args customer.CustomerServiceAssignScheduleArgs
	_args.Req = req
	var _result customer.CustomerServiceAssignScheduleResult
	if err = p.c.Call(ctx, "AssignSchedule", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListScheduleGrid(ctx context.Context, req *customer.ListScheduleGridReq) (r *customer.ListScheduleGridResp, err error) {
	var _args customer.CustomerServiceListScheduleGridArgs
	_args.Req = req
	var _result customer.CustomerServiceListScheduleGridResult
	if err = p.c.Call(ctx, "ListScheduleGrid", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpsertScheduleCell(ctx context.Context, req *customer.UpsertScheduleCellReq) (r *customer.UpsertScheduleCellResp, err error) {
	var _args customer.CustomerServiceUpsertScheduleCellArgs
	_args.Req = req
	var _result customer.CustomerServiceUpsertScheduleCellResult
	if err = p.c.Call(ctx, "UpsertScheduleCell", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AutoSchedule(ctx context.Context, req *customer.AutoScheduleReq) (r *customer.AutoScheduleResp, err error) {
	var _args customer.CustomerServiceAutoScheduleArgs
	_args.Req = req
	var _result customer.CustomerServiceAutoScheduleResult
	if err = p.c.Call(ctx, "AutoSchedule", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AssignCustomer(ctx context.Context, req *customer.AssignCustomerReq) (r *customer.AssignCustomerResp, err error) {
	var _args customer.CustomerServiceAssignCustomerArgs
	_args.Req = req
	var _result customer.CustomerServiceAssignCustomerResult
	if err = p.c.Call(ctx, "AssignCustomer", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateConversation(ctx context.Context, req *customer.CreateConversationReq) (r *customer.CreateConversationResp, err error) {
	var _args customer.CustomerServiceCreateConversationArgs
	_args.Req = req
	var _result customer.CustomerServiceCreateConversationResult
	if err = p.c.Call(ctx, "CreateConversation", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) EndConversation(ctx context.Context, req *customer.EndConversationReq) (r *customer.EndConversationResp, err error) {
	var _args customer.CustomerServiceEndConversationArgs
	_args.Req = req
	var _result customer.CustomerServiceEndConversationResult
	if err = p.c.Call(ctx, "EndConversation", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) TransferConversation(ctx context.Context, req *customer.TransferConversationReq) (r *customer.TransferConversationResp, err error) {
	var _args customer.CustomerServiceTransferConversationArgs
	_args.Req = req
	var _result customer.CustomerServiceTransferConversationResult
	if err = p.c.Call(ctx, "TransferConversation", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ApplyLeaveTransfer(ctx context.Context, req *customer.ApplyLeaveTransferReq) (r *customer.ApplyLeaveTransferResp, err error) {
	var _args customer.CustomerServiceApplyLeaveTransferArgs
	_args.Req = req
	var _result customer.CustomerServiceApplyLeaveTransferResult
	if err = p.c.Call(ctx, "ApplyLeaveTransfer", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ApproveLeaveTransfer(ctx context.Context, req *customer.ApproveLeaveTransferReq) (r *customer.ApproveLeaveTransferResp, err error) {
	var _args customer.CustomerServiceApproveLeaveTransferArgs
	_args.Req = req
	var _result customer.CustomerServiceApproveLeaveTransferResult
	if err = p.c.Call(ctx, "ApproveLeaveTransfer", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetLeaveTransfer(ctx context.Context, req *customer.GetLeaveTransferReq) (r *customer.GetLeaveTransferResp, err error) {
	var _args customer.CustomerServiceGetLeaveTransferArgs
	_args.Req = req
	var _result customer.CustomerServiceGetLeaveTransferResult
	if err = p.c.Call(ctx, "GetLeaveTransfer", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListLeaveTransfer(ctx context.Context, req *customer.ListLeaveTransferReq) (r *customer.ListLeaveTransferResp, err error) {
	var _args customer.CustomerServiceListLeaveTransferArgs
	_args.Req = req
	var _result customer.CustomerServiceListLeaveTransferResult
	if err = p.c.Call(ctx, "ListLeaveTransfer", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetLeaveAuditLog(ctx context.Context, req *customer.GetLeaveAuditLogReq) (r *customer.GetLeaveAuditLogResp, err error) {
	var _args customer.CustomerServiceGetLeaveAuditLogArgs
	_args.Req = req
	var _result customer.CustomerServiceGetLeaveAuditLogResult
	if err = p.c.Call(ctx, "GetLeaveAuditLog", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ApplyChainSwap(ctx context.Context, req *customer.ApplyChainSwapReq) (r *customer.ApplyChainSwapResp, err error) {
	var _args customer.CustomerServiceApplyChainSwapArgs
	_args.Req = req
	var _result customer.CustomerServiceApplyChainSwapResult
	if err = p.c.Call(ctx, "ApplyChainSwap", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ApproveChainSwap(ctx context.Context, req *customer.ApproveChainSwapReq) (r *customer.ApproveChainSwapResp, err error) {
	var _args customer.CustomerServiceApproveChainSwapArgs
	_args.Req = req
	var _result customer.CustomerServiceApproveChainSwapResult
	if err = p.c.Call(ctx, "ApproveChainSwap", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListChainSwap(ctx context.Context, req *customer.ListChainSwapReq) (r *customer.ListChainSwapResp, err error) {
	var _args customer.CustomerServiceListChainSwapArgs
	_args.Req = req
	var _result customer.CustomerServiceListChainSwapResult
	if err = p.c.Call(ctx, "ListChainSwap", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetChainSwap(ctx context.Context, req *customer.GetChainSwapReq) (r *customer.GetChainSwapResp, err error) {
	var _args customer.CustomerServiceGetChainSwapArgs
	_args.Req = req
	var _result customer.CustomerServiceGetChainSwapResult
	if err = p.c.Call(ctx, "GetChainSwap", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Heartbeat(ctx context.Context, req *customer.HeartbeatReq) (r *customer.HeartbeatResp, err error) {
	var _args customer.CustomerServiceHeartbeatArgs
	_args.Req = req
	var _result customer.CustomerServiceHeartbeatResult
	if err = p.c.Call(ctx, "Heartbeat", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListOnlineCustomers(ctx context.Context, req *customer.ListOnlineCustomersReq) (r *customer.ListOnlineCustomersResp, err error) {
	var _args customer.CustomerServiceListOnlineCustomersArgs
	_args.Req = req
	var _result customer.CustomerServiceListOnlineCustomersResult
	if err = p.c.Call(ctx, "ListOnlineCustomers", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetSwapCandidates(ctx context.Context, req *customer.GetSwapCandidatesReq) (r *customer.GetSwapCandidatesResp, err error) {
	var _args customer.CustomerServiceGetSwapCandidatesArgs
	_args.Req = req
	var _result customer.CustomerServiceGetSwapCandidatesResult
	if err = p.c.Call(ctx, "GetSwapCandidates", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CheckSwapConflict(ctx context.Context, req *customer.CheckSwapConflictReq) (r *customer.CheckSwapConflictResp, err error) {
	var _args customer.CustomerServiceCheckSwapConflictArgs
	_args.Req = req
	var _result customer.CustomerServiceCheckSwapConflictResult
	if err = p.c.Call(ctx, "CheckSwapConflict", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListConversation(ctx context.Context, req *customer.ListConversationReq) (r *customer.ListConversationResp, err error) {
	var _args customer.CustomerServiceListConversationArgs
	_args.Req = req
	var _result customer.CustomerServiceListConversationResult
	if err = p.c.Call(ctx, "ListConversation", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListConversationHistory(ctx context.Context, req *customer.ListConversationHistoryReq) (r *customer.ListConversationResp, err error) {
	var _args customer.CustomerServiceListConversationHistoryArgs
	_args.Req = req
	var _result customer.CustomerServiceListConversationHistoryResult
	if err = p.c.Call(ctx, "ListConversationHistory", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListConversationMessage(ctx context.Context, req *customer.ListConversationMessageReq) (r *customer.ListConversationMessageResp, err error) {
	var _args customer.CustomerServiceListConversationMessageArgs
	_args.Req = req
	var _result customer.CustomerServiceListConversationMessageResult
	if err = p.c.Call(ctx, "ListConversationMessage", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SendConversationMessage(ctx context.Context, req *customer.SendConversationMessageReq) (r *customer.SendConversationMessageResp, err error) {
	var _args customer.CustomerServiceSendConversationMessageArgs
	_args.Req = req
	var _result customer.CustomerServiceSendConversationMessageResult
	if err = p.c.Call(ctx, "SendConversationMessage", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListQuickReply(ctx context.Context, req *customer.ListQuickReplyReq) (r *customer.ListQuickReplyResp, err error) {
	var _args customer.CustomerServiceListQuickReplyArgs
	_args.Req = req
	var _result customer.CustomerServiceListQuickReplyResult
	if err = p.c.Call(ctx, "ListQuickReply", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateQuickReply(ctx context.Context, req *customer.CreateQuickReplyReq) (r *customer.CreateQuickReplyResp, err error) {
	var _args customer.CustomerServiceCreateQuickReplyArgs
	_args.Req = req
	var _result customer.CustomerServiceCreateQuickReplyResult
	if err = p.c.Call(ctx, "CreateQuickReply", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateQuickReply(ctx context.Context, req *customer.UpdateQuickReplyReq) (r *customer.UpdateQuickReplyResp, err error) {
	var _args customer.CustomerServiceUpdateQuickReplyArgs
	_args.Req = req
	var _result customer.CustomerServiceUpdateQuickReplyResult
	if err = p.c.Call(ctx, "UpdateQuickReply", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteQuickReply(ctx context.Context, req *customer.DeleteQuickReplyReq) (r *customer.DeleteQuickReplyResp, err error) {
	var _args customer.CustomerServiceDeleteQuickReplyArgs
	_args.Req = req
	var _result customer.CustomerServiceDeleteQuickReplyResult
	if err = p.c.Call(ctx, "DeleteQuickReply", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateConvCategory(ctx context.Context, req *customer.CreateConvCategoryReq) (r *customer.CreateConvCategoryResp, err error) {
	var _args customer.CustomerServiceCreateConvCategoryArgs
	_args.Req = req
	var _result customer.CustomerServiceCreateConvCategoryResult
	if err = p.c.Call(ctx, "CreateConvCategory", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListConvCategory(ctx context.Context, req *customer.ListConvCategoryReq) (r *customer.ListConvCategoryResp, err error) {
	var _args customer.CustomerServiceListConvCategoryArgs
	_args.Req = req
	var _result customer.CustomerServiceListConvCategoryResult
	if err = p.c.Call(ctx, "ListConvCategory", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateConversationClassify(ctx context.Context, req *customer.UpdateConversationClassifyReq) (r *customer.UpdateConversationClassifyResp, err error) {
	var _args customer.CustomerServiceUpdateConversationClassifyArgs
	_args.Req = req
	var _result customer.CustomerServiceUpdateConversationClassifyResult
	if err = p.c.Call(ctx, "UpdateConversationClassify", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateConvTag(ctx context.Context, req *customer.CreateConvTagReq) (r *customer.CreateConvTagResp, err error) {
	var _args customer.CustomerServiceCreateConvTagArgs
	_args.Req = req
	var _result customer.CustomerServiceCreateConvTagResult
	if err = p.c.Call(ctx, "CreateConvTag", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListConvTag(ctx context.Context, req *customer.ListConvTagReq) (r *customer.ListConvTagResp, err error) {
	var _args customer.CustomerServiceListConvTagArgs
	_args.Req = req
	var _result customer.CustomerServiceListConvTagResult
	if err = p.c.Call(ctx, "ListConvTag", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateConvTag(ctx context.Context, req *customer.UpdateConvTagReq) (r *customer.UpdateConvTagResp, err error) {
	var _args customer.CustomerServiceUpdateConvTagArgs
	_args.Req = req
	var _result customer.CustomerServiceUpdateConvTagResult
	if err = p.c.Call(ctx, "UpdateConvTag", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteConvTag(ctx context.Context, req *customer.DeleteConvTagReq) (r *customer.DeleteConvTagResp, err error) {
	var _args customer.CustomerServiceDeleteConvTagArgs
	_args.Req = req
	var _result customer.CustomerServiceDeleteConvTagResult
	if err = p.c.Call(ctx, "DeleteConvTag", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetConversationStats(ctx context.Context, req *customer.GetConversationStatsReq) (r *customer.GetConversationStatsResp, err error) {
	var _args customer.CustomerServiceGetConversationStatsArgs
	_args.Req = req
	var _result customer.CustomerServiceGetConversationStatsResult
	if err = p.c.Call(ctx, "GetConversationStats", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetConversationMonitor(ctx context.Context, req *customer.GetConversationMonitorReq) (r *customer.GetConversationMonitorResp, err error) {
	var _args customer.CustomerServiceGetConversationMonitorArgs
	_args.Req = req
	var _result customer.CustomerServiceGetConversationMonitorResult
	if err = p.c.Call(ctx, "GetConversationMonitor", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ExportConversations(ctx context.Context, req *customer.ExportConversationsReq) (r *customer.ExportConversationsResp, err error) {
	var _args customer.CustomerServiceExportConversationsArgs
	_args.Req = req
	var _result customer.CustomerServiceExportConversationsResult
	if err = p.c.Call(ctx, "ExportConversations", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) MsgAutoClassify(ctx context.Context, req *customer.MsgAutoClassifyReq) (r *customer.MsgAutoClassifyResp, err error) {
	var _args customer.CustomerServiceMsgAutoClassifyArgs
	_args.Req = req
	var _result customer.CustomerServiceMsgAutoClassifyResult
	if err = p.c.Call(ctx, "MsgAutoClassify", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AdjustMsgClassify(ctx context.Context, req *customer.AdjustMsgClassifyReq) (r *customer.AdjustMsgClassifyResp, err error) {
	var _args customer.CustomerServiceAdjustMsgClassifyArgs
	_args.Req = req
	var _result customer.CustomerServiceAdjustMsgClassifyResult
	if err = p.c.Call(ctx, "AdjustMsgClassify", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetClassifyStats(ctx context.Context, req *customer.GetClassifyStatsReq) (r *customer.GetClassifyStatsResp, err error) {
	var _args customer.CustomerServiceGetClassifyStatsArgs
	_args.Req = req
	var _result customer.CustomerServiceGetClassifyStatsResult
	if err = p.c.Call(ctx, "GetClassifyStats", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateMsgCategory(ctx context.Context, req *customer.CreateMsgCategoryReq) (r *customer.CreateMsgCategoryResp, err error) {
	var _args customer.CustomerServiceCreateMsgCategoryArgs
	_args.Req = req
	var _result customer.CustomerServiceCreateMsgCategoryResult
	if err = p.c.Call(ctx, "CreateMsgCategory", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListMsgCategory(ctx context.Context, req *customer.ListMsgCategoryReq) (r *customer.ListMsgCategoryResp, err error) {
	var _args customer.CustomerServiceListMsgCategoryArgs
	_args.Req = req
	var _result customer.CustomerServiceListMsgCategoryResult
	if err = p.c.Call(ctx, "ListMsgCategory", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateMsgCategory(ctx context.Context, req *customer.UpdateMsgCategoryReq) (r *customer.UpdateMsgCategoryResp, err error) {
	var _args customer.CustomerServiceUpdateMsgCategoryArgs
	_args.Req = req
	var _result customer.CustomerServiceUpdateMsgCategoryResult
	if err = p.c.Call(ctx, "UpdateMsgCategory", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteMsgCategory(ctx context.Context, req *customer.DeleteMsgCategoryReq) (r *customer.DeleteMsgCategoryResp, err error) {
	var _args customer.CustomerServiceDeleteMsgCategoryArgs
	_args.Req = req
	var _result customer.CustomerServiceDeleteMsgCategoryResult
	if err = p.c.Call(ctx, "DeleteMsgCategory", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Login(ctx context.Context, req *customer.LoginReq) (r *customer.LoginResp, err error) {
	var _args customer.CustomerServiceLoginArgs
	_args.Req = req
	var _result customer.CustomerServiceLoginResult
	if err = p.c.Call(ctx, "Login", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetCurrentUser(ctx context.Context, req *customer.GetCurrentUserReq) (r *customer.GetCurrentUserResp, err error) {
	var _args customer.CustomerServiceGetCurrentUserArgs
	_args.Req = req
	var _result customer.CustomerServiceGetCurrentUserResult
	if err = p.c.Call(ctx, "GetCurrentUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Register(ctx context.Context, req *customer.RegisterReq) (r *customer.RegisterResp, err error) {
	var _args customer.CustomerServiceRegisterArgs
	_args.Req = req
	var _result customer.CustomerServiceRegisterResult
	if err = p.c.Call(ctx, "Register", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Logout(ctx context.Context, req *customer.LogoutReq) (r *customer.LogoutResp, err error) {
	var _args customer.CustomerServiceLogoutArgs
	_args.Req = req
	var _result customer.CustomerServiceLogoutResult
	if err = p.c.Call(ctx, "Logout", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) EncryptMessage(ctx context.Context, req *customer.EncryptMessageReq) (r *customer.EncryptMessageResp, err error) {
	var _args customer.CustomerServiceEncryptMessageArgs
	_args.Req = req
	var _result customer.CustomerServiceEncryptMessageResult
	if err = p.c.Call(ctx, "EncryptMessage", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DecryptMessage(ctx context.Context, req *customer.DecryptMessageReq) (r *customer.DecryptMessageResp, err error) {
	var _args customer.CustomerServiceDecryptMessageArgs
	_args.Req = req
	var _result customer.CustomerServiceDecryptMessageResult
	if err = p.c.Call(ctx, "DecryptMessage", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DesensitizeMessage(ctx context.Context, req *customer.DesensitizeMessageReq) (r *customer.DesensitizeMessageResp, err error) {
	var _args customer.CustomerServiceDesensitizeMessageArgs
	_args.Req = req
	var _result customer.CustomerServiceDesensitizeMessageResult
	if err = p.c.Call(ctx, "DesensitizeMessage", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ArchiveConversations(ctx context.Context, req *customer.ArchiveConversationsReq) (r *customer.ArchiveConversationsResp, err error) {
	var _args customer.CustomerServiceArchiveConversationsArgs
	_args.Req = req
	var _result customer.CustomerServiceArchiveConversationsResult
	if err = p.c.Call(ctx, "ArchiveConversations", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetArchiveTask(ctx context.Context, req *customer.GetArchiveTaskReq) (r *customer.GetArchiveTaskResp, err error) {
	var _args customer.CustomerServiceGetArchiveTaskArgs
	_args.Req = req
	var _result customer.CustomerServiceGetArchiveTaskResult
	if err = p.c.Call(ctx, "GetArchiveTask", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) QueryArchivedConversation(ctx context.Context, req *customer.QueryArchivedConversationReq) (r *customer.QueryArchivedConversationResp, err error) {
	var _args customer.CustomerServiceQueryArchivedConversationArgs
	_args.Req = req
	var _result customer.CustomerServiceQueryArchivedConversationResult
	if err = p.c.Call(ctx, "QueryArchivedConversation", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
